%YAML:1.0

img_dataset_dir: /home/yeren/euroc_dataset/mav0/cam0
img_gt_file: /home/yeren/euroc_dataset/mav0/imu0/data.csv
imu_dataset_dir: /home/yeren/euroc_dataset/mav0/imu0/
imu_gt_file: /home/yeren/euroc_dataset/mav0/imu0/data.csv
source_type: 0
num_features: 150
rect_size: 10
opt_win_size: 9
match_threshold: 50
feature_amount_threshold: 120
inliners_threshold: 50
dis_threshold: 100.0