%YAML:1.0

img_dataset_dir: /home/yeren/sfm_learn/datasets/fountain_dense_images
img_gt_file: /home/yeren/sfm_learn/datasets/fountain_dense_cameras/0000.png.camera
source_type: 0
num_features: 150
rect_size: 10
opt_win_size: 9
match_threshold: 50
feature_amount_threshold: 120
inliners_threshold: 50
dis_threshold: 100.0